[package]
name = "kaf9s-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.26.0", features = ["cmake-build", "ssl"]}
keyring = "0.10.1"